### ISSUE TITLE
API returning outdated data

### ISSUE THREAD

**Issue by Mezy** [SpiGetOrg/Spiget#23] opened 2019-12-12 12:49 UTC
Plugin: https://www.spigotmc.org/resources/uhccore-automated-uhc-for-minecraft-1-8-8-1-15.47572/
API Request: https://api.spiget.org/v2/resources/47572/versions/latest

As you can see on the plugin page the latest version of the plugin in 1.15. But when checking the Spiget API it returns 1.14.9.

**Comment by aft2d** [comment] 2019-12-12 14:35
Duplicate of #15 ?

**Comment by InventivetalentDev** [comment] 2019-12-12 14:43
@Mezy Triggered a manual update, should refresh in the next run.

**Closed as completed by InventivetalentDev** 2019-12-12 14:43 UTC

**Comment by Mezy** [comment] 2019-12-12 15:55
That worked, thanks!
